In [1]:
my_list = [1,2,3,4]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [6]:
arr_2 = np.array(my_mat)

In [7]:
arr_2 # 2 sets of brackets showing it's a 2D array with 3x3 rows and columns format

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(9) #  Returns an array of zeros and 1D if 1 number gives

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,4)) # Pass a tuple of the dimensions you want. Rows, Cloumns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

**Linspace returns evenly spaced numbers over a specified region. Range returns integers out of [start,stop) in a given interval size while linspace takes third argument that you want and separetes start and stop appropriately.**

In [13]:
np.linspace(0,5,10) # Between 0 to 5 it sends 10 evenly spaced points.

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

**# of brackets tells the dimension of the array at the opening or the closing. At a 2D array you'd find [[ ]]at the beginning and end.**
Range takes the third argument as the step size you want. Whereas linspace takes the third argument as the number of points you want.

In [15]:
# Creating an IDENTITY Matrix - A 2D matrix with rows = columns and anything except primary diagonal = 0
np.eye(4) # 4 being the number of rows and columns in the identity matrix that we are making


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**To Create Arrays of Random Numbers**

In [18]:
np.random.rand(5) # Creates an array of the given shape that we pass in.

array([0.0424847 , 0.11719505, 0.14544958, 0.49237554, 0.64041937])

In [19]:
np.random.rand(5,5)

array([[0.01145236, 0.11185887, 0.05473555, 0.41841496, 0.43100872],
       [0.23063281, 0.61258917, 0.36181319, 0.25099951, 0.11340042],
       [0.61082597, 0.65639998, 0.94536185, 0.29033947, 0.47767218],
       [0.8987636 , 0.75502282, 0.19058515, 0.81036327, 0.92756919],
       [0.55441711, 0.39298753, 0.43249307, 0.96607119, 0.33998867]])

**# Randn Returns numbers not from a uniform distribution but from zero to 1 but normal distribution 
centred around zero**

In [25]:
np.random.randn(4,4) # No need to pass tuple, just the dimensions.

array([[ 0.27935317,  0.63644148,  1.88378677, -1.61438365],
       [ 1.53581165, -0.14775585, -0.08846581, -1.14523466],
       [ 0.94300594, -0.51004852, -0.65958085, -1.98202637],
       [ 0.9549013 ,  0.98817001, -0.69788578, -0.91630268]])

In [26]:
np.random.randint(1,100) # Lowest inclusive and highest exclusive to be returned. [low,high,size]

91

In [30]:
np.random.randint(1,100,4) # Here we have specified size as well. By default 3rd parameter size is 1.

array([68, 19, 26, 67])

In [34]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr=np.random.randint(0,50,10)
ranarr

array([ 7, 20, 32, 37, 37,  8,  5, 46, 29, 37])

# Reshape an Array 
**Returns array having same data but in a new shape**

In [41]:
arr.reshape(5,5) # Passing reshape(number_of_rows,number_of_columns)

# Also you need to fill out all the elements in the new array of exact same size, nothing less, nothing more.
# Number of rows*Number of Columns in the reshaped array = Number of elements in the original array being reshaped.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr

array([ 7, 20, 32, 37, 37,  8,  5, 46, 29, 37])

In [45]:
ranarr.max()

46

In [46]:
ranarr.min()

5

In [47]:
ranarr.argmax()  # Gets the index location of the maximum value

7

In [48]:
ranarr.argmin() # Geths the index location of the minimum value

6

In [58]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr.shape # (25,) it means that arr was just a 1D vector

(5, 5)

In [55]:
arr = arr.reshape(5,5)

In [56]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
arr.shape # No parantheses

(5, 5)

In [61]:
arr.dtype # Returns datatype in the array.

dtype('int64')

In [62]:
#Shortcut for having randint or another method inside numpy that you know you will be using
# regularly is to import it

In [66]:
from numpy.random import randint as ri

In [69]:
ri(1,20,10) # direct use of randint without np.random.randint()

array([18, 15, 17,  4,  8,  4, 12,  9, 14, 10])