In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

In [ ]:
#  Simplest way to pick an element or some of the elements from an array is similar to indexing in a python list.
arr[8] # Gives value at the index 8

In [ ]:
#  Slice Notations [start:stop]
arr[1:5] # 1 inclusive and 5 exclusive

In [ ]:
#  Another Example of Slicing
arr[0:5]

In [ ]:
# To have everything from beginning to the index 6 we use the following syntax on a numpy array :
print(arr[:6]) # No need to define the starting point and this basically means arr[0:6]
# To have everything from a 5th index to the last we use the following syntax on a numpy array :
print(arr[5:])

# Broadcasting the Value
**Numpy arrays differ from normal python list due to their ability to broadcast.**

In [ ]:
arr[0:5] = 100 # Broacasts the value 100 to first 5 digits.

In [ ]:
arr

In [ ]:
#  Reset the array
arr = np.arange(0,11)

In [ ]:
arr

In [ ]:
slice_of_arr = arr[0:6]

In [ ]:
slice_of_arr

In [ ]:
# To grab everything in the slice 
slice_of_arr[:]

In [ ]:
#  Broadcasting after grabbing everything in the array 
slice_of_arr[:] = 99

In [ ]:
slice_of_arr

In [ ]:
arr

In [ ]:
# Notice above how not only slice_of_arr got changed due to the broadcast but the array arr was also changed.
#  Slice and the original array both got changed in terms of values.
#  Data is not copied but rather just copied or pointed from original array.
#  Reason behind such behaviour is that to prevent memory issues while dealing with large arrays.
#  It basically means numpy prefers not setting copies of arrays and would rather point slices to their original parent arrays.
#  Use copy() method which is array_name.copy()

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy

In [ ]:
arr_copy[0:5] = 23

In [ ]:
arr

In [ ]:
arr_copy #Since we have copied now we can see that arr and arr_copy would be different even after broadcasting.
# Original array remains unaffected despite changes on the copied array.
#  Main idea here is that if you grab the actual slice of the array and set it as variable without calling the method copy
#  on the array then you are just seeing the link to original array and changes on slice would reflect on original/parent array.

# 2D Array/Matrix

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
arr_2d # REMEMBER If having confusion regarding dimensions of the matrix just call shape.

In [ ]:
arr_2d.shape # 3 rows, 3 columns

In [ ]:
# Two general formats for grabbing elements from a 2D array or matrix format :
#  (i) Double Bracket Format (ii) Single Bracket Format with comma (Recommended)

#  (i) Double Bracket Format
arr_2d[0][:] # Gives all the elements inside the 0th index of array arr.
# arr_2d[0][:] Also works

In [ ]:
arr_2d[1][2] # Gives the element at index 2 of the 1st index of arr_2d i.e. 30

In [ ]:
# (ii) Single Bracket Format with comma (Recommended) : Removes [][] 2 square brackets with a tuple kind (x,y) format
# To print 30 we do the following 1st row and 2nd index
arr_2d[1,2]

In [ ]:
#  Say we want sub matrices from the matrix arr_2d
arr_2d[:3,1:] # Everything upto the third row, and anything from column 1 onwards.

In [ ]:
arr_2d[1:,:]

# Conditional Selection

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

In [ ]:
# Taking the array arr and comapring it using comparison operators to get a full boolean array out of this.
bool_arr = arr > 5
'''
1. Getting the array and using a comparison operator on it will actually return a boolean array.
2. An array with boolean values in response to our condition.
3. Now we can use the boolean array to actually index or conditionally select elements from the original array where boolean
array is true.

'''

In [ ]:
bool_arr

In [ ]:
arr[bool_arr] # Gives us only the results which are only true.

In [ ]:
# Doing what's described above in one line will be 
arr[arr<3] # arr[comaprison condition] Get used to this notation we use this a lot especially in Pandas!

# Exercise

1. Create a new 2d array np.arange(50).reshape(5,10).
2. Grab any 2sub matrices from the 5x10 chunk.


In [59]:
arr_2d = np.arange(50).reshape(5,10)

In [60]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [61]:
# Selecting 11 to 35
arr_2d[1:4,1:6]# Keep in mind it is exclusive for the end value in the start:end format of indexing.

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [62]:
# Selecting 5-49
arr_2d[0:,5:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])