# NumPy Operations

 - **Array With Array**
 - **Array With Scalars**
 - **Universal Array Functions**

## Arithmetic

We can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# Add,Subtract,Multiply 2 arrays together element by element
print("Add      :",arr + arr)
print("Subtract : ",arr - arr)
print("Multiply : ",arr * arr)

Add      : [ 0  2  4  6  8 10 12 14 16 18 20]
Subtract :  [0 0 0 0 0 0 0 0 0 0 0]
Multiply :  [  0   1   4   9  16  25  36  49  64  81 100]


In [9]:
'''
 Array with scalar operations : Numpy broadcasts the number to every element in the array so that operation occurs
 on an element by element basis.
'''
print("Scalar Add      :",arr + 100)
print("Scalar Subtract : ",arr - 100)
print("Scalar Multiply : ",arr * 100)

Scalar Add      : [100 101 102 103 104 105 106 107 108 109 110]
Scalar Subtract :  [-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
Scalar Multiply :  [   0  100  200  300  400  500  600  700  800  900 1000]


In [10]:
# Numpy issues a warning when there is a case of 0/0 or other similar cases and results in nan in that place.
# Code will continue to run with a warning. 1/0 puts inf in the array instead of nan.
arr / arr

c:\program files\python37\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
arr ** 2 #Powers in array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

# Universal Array Functions
Numpy has many universal array functions.
These are just mathematical operations that we can used to perform an operation and broadcast across the entire array.
Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [14]:
np.max(arr) # Similar to arr.max() i.e. calling method max() on the array arr

10

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [16]:
np.log(arr)

c:\program files\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])